info.description: configserver-main
---
spring:
  profiles: cloud
service:
  definition:
    metadata:
      uri: http://${spring.application.name}.${application.domain:cfapps.io}
---
spring:
  profiles: prod
service:
  definition:
    metadata:
      uri: http://${spring.application.name}.${application.domain:cfapps.io}/prod
